import {StyleSheet} from 'react-native';
import Colors from '../../constants/Colors';

const styles = StyleSheet.create({
  root: {
    justifyContent: 'space-between',
    flex: 1,
    backgroundColor: Colors.white,
  },
  image: {
    height: 330,
    width: '100%',
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 18,
  },

  detailCard: {
    marginTop: -33,
    // height: 106,
    backgroundColor: Colors.white,
    borderRadius: 8,
    paddingTop: 9,
    paddingLeft: 18,
    paddingRight: 18,
    paddingBottom: 18,
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.16,
    shadowRadius: 6,
    elevation: 5,
  },
  textBold: {
    fontFamily: 'Inter-Regular',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 20,
    lineHeight: 24,
    color: Colors.black,
    opacity: 0.82,
    textAlign: 'left',
  },
  textSemiBold: {
    fontFamily: 'Inter-Regular',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 19.36,
    color: Colors.darkBlack,
    opacity: 0.82,
  },
  textNormal: {
    fontFamily: 'Inter-Regular',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 19.36,
    color: Colors.black,
    opacity: 0.8,
    marginBottom: 5,
  },

  bookNowButtonCard: {
    backgroundColor: Colors.white,
    flexDirection: 'row',
    height: 60,
    width: '93%',
    alignSelf: 'center',
    justifyContent: 'space-between',
    borderRadius: 10,
    marginHorizontal: 5,

    alignItems: 'center',
  },
  location: {
    fontFamily: 'Inter-Regular',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 16,
    lineHeight: 19.36,
    color: Colors.black,
    opacity: 0.8,
  },
  detailsCard: {
    marginHorizontal: 16,
    marginBottom: 16,
    borderRadius: 8,
    // elevation: 4,
    // height: 180,
    // paddingHorizontal: 12,
    padding: 8,
    backgroundColor: Colors.white,
  },

  detailRow: {
    flexDirection: 'row',
    flex: 1,
    justifyContent: 'space-between',
  },
  fontRegular: {
    fontFamily: 'Inter-Regular',
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 19.36,
    color: Colors.black,
  },
  fontSemibold: {
    fontFamily: 'Inter-Regular',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 19.36,
    color: Colors.darkBlack,
    opacity: 0.82,
    marginBottom: 5,
  },
  amenitiesCard: {
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  amenitiesText: {
    textAlign: 'center',
    fontSize: 12,
    fontFamily: 'Inter-Regular',
    color: '#2A2A2A',
    marginLeft: 3,
  },
  Icons: {
    marginTop: 8,
    height: 50,
    width: 50,
    marginLeft: 10,
  },
  AmenitiesCard: {
    borderWidth: 1,
    borderColor: 'white',
    borderRadius: 8,
    backgroundColor: 'white',
    paddingHorizontal: 8,
    paddingVertical: 12,
    marginTop: 20,
    marginBottom: 28,
    elevation: 5,
  },
  Amenities: {
    fontFamily: 'Inter-Bold',
    fontSize: 20,
    color: 'black',
    marginLeft: 14,
  },
  tabstructure: {
    paddingHorizontal: 8 / -2,
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
});

export default styles;
